enum CanvasEnum {
    ADD_NEW_CLASS = 'ADD_NEW_CLASS',
    ADD_NEW_ASSOCIATION = 'ADD_NEW_ASSOCIATION',
    ADD_NEW_CURRENTLY_DRAWING_RELATIONSHIP = 'ADD_NEW_CURRENTLY_DRAWING_RELATIONSHIP',
    EDIT_CURRENTLY_DRAWING_RELATIONSHIP = 'EDIT_CURRENTLY_DRAWING_RELATIONSHIP'
}

export default CanvasEnum;