enum CanvasEnum {
    ADD_NEW_CLASS = 'ADD_NEW_CLASS',
    ADD_NEW_FULL_CLASS = 'ADD_NEW_FULL_CLASS',
    ADD_NEW_ASSOCIATION = 'ADD_NEW_ASSOCIATION',
    SELECT_ELEMENT = 'SELECT_ELEMENT',
    UPDATE_ELEMENT = 'UPDATE_ELEMENT'
}

export default CanvasEnum;