enum CanvasActionEnum {
    SELECT_NEW_ELEMENT = 'SELECT_NEW_ELEMENT',
    IS_MOUSE_DOWN = 'MOUSE_DOWN',
    NEW_CANVAS_OPERATION = 'NEW_CANVAS_OPERATION',
    SET_DEFAULT_RELATIONSHIP_TYPE = 'SET_DEFAULT_RELATIONSHIP_TYPE',
    SET_DIAGRAM_TYPE = 'SET_DIAGRAM_TYPE'
}

export default CanvasActionEnum;