enum CanvasOperationEnum {
    DRAWING_NEW_RELATION = 'DRAWING_NEW_RELATION',
    UPDATE_RELATION = 'UPDATE_RELATION',
    RESIZE_ELEMENT_LEFT = 'RESIZE_ELEMENT_LEFT',
    RESIZE_ELEMENT_RIGHT = 'RESIZE_ELEMENT_RIGHT',
    MOVE_ELEMENT = 'MOVE_ELEMENT',
    MOVE_RELATIONSHIP_SEGMENT = 'MOVE_RELATIONSHIP_SEGMENT',
    MOVE_RELATIONSHIP_HEAD = 'MOVE_RELATIONSHIP_HEAD',
    MOVE_RELATIONSHIP_TAIL = 'MOVE_RELATIONSHIP_TAIL',
    NONE = 'NONE'
}

export default CanvasOperationEnum;