enum CanvasOperationEnum {
    DRAWING_NEW_RELATION = 'DRAWING_NEW_RELATION',
    UPDATE_RELATION = 'UPDATE_RELATION',
    MOVE_CLASS = 'MOVE_CLASS',
    RESIZE_ELEMENT_LEFT = 'RESIZE_ELEMENT_LEFT',
    RESIZE_ELEMENT_RIGHT = 'RESIZE_ELEMENT_RIGHT',
    NONE = 'NONE'
}

export default CanvasOperationEnum;