enum ClassDiagramElementsEnum {
    CLASS = 'CLASS',
    ASSOCIATION = 'ASSOCIATION',
    DEPENDENCY = 'DEPENDENCY',
    AGGREGATION = 'AGGREGATION',
    COMPOSITION = 'COMPOSITION',
    INHERITANCE = 'INHERITANCE',
    INTERFACE = 'INTERFACE',
    UTILITY = 'UTILITY',
    ENUMERATION = 'ENUMERATION',
    DATA_TYPE = 'DATA_TYPE'
}

export default ClassDiagramElementsEnum;