enum ClassDiagramElementsEnum {
    CLASS = 'CLASS',
    ASSOCIATION = 'ASSOCIATION',
    DEPENDENCY = 'DEPENDENCY',
    AGGREGATION = 'AGGREGATION',
    COMPOSITION = 'COMPOSITION',
    INHERITANCE = 'INHERITANCE',
    INTERFACE = 'INTERFACE'
}

export default ClassDiagramElementsEnum;