enum ClassDiagramActionEnum {
    ADD_NEW_CLASS = 'ADD_NEW_CLASS',
    UPDATE_CLASS = 'UPDATE_CLASS',
    ADD_NEW_CLASS_METHOD = 'ADD_NEW_CLASS_METHOD',
    UPDATE_CLASS_METHOD = 'UPDATE_CLASS_METHOD',
    REMOVE_CLASS_METHOD = 'REMOVE_CLASS_METHOD',
    ADD_NEW_CLASS_PROPERTY = 'ADD_NEW_CLASS_PROPERTY',
    UPDATE_CLASS_PROPERTY = 'UPDATE_CLASS_PROPERTY',
    REMOVE_CLASS_PROPERTY = 'REMOVE_CLASS_PROPERTY'
}

export default ClassDiagramActionEnum;