enum ClassDiagramActionEnum {
    ADD_NEW_CLASS = 'ADD_NEW_CLASS',
    UPDATE_CLASS = 'UPDATE_CLASS',
    ADD_NEW_CLASS_METHOD = 'ADD_NEW_CLASS_METHOD',
    UPDATE_CLASS_METHOD = 'UPDATE_CLASS_METHOD',
    REMOVE_CLASS_METHOD = 'REMOVE_CLASS_METHOD',
    ADD_NEW_CLASS_PROPERTY = 'ADD_NEW_CLASS_PROPERTY',
    UPDATE_CLASS_PROPERTY = 'UPDATE_CLASS_PROPERTY',
    REMOVE_CLASS_PROPERTY = 'REMOVE_CLASS_PROPERTY',
    ADD_NEW_RELATIONSHIP = 'ADD_NEW_RELATIONSHIP',
    UPDATE_RELATIONSHIP = 'UPDATE_RELATIONSHIP',
    ADD_NEW_RELATIONSHIP_SEGMENT = 'ADD_NEW_RELATIONSHIP_SEGMENT',
    UPDATE_RELATIONSHIP_SEGMENT = 'UPDATE_RELATIONSHIP_SEGMENT',
    ADD_NEW_INTERFACE = 'ADD_NEW_INTERFACE',
    ADD_NEW_INTERFACE_PROPERTY = 'ADD_NEW_INTERFACE_PROPERTY',
    ADD_NEW_INTERFACE_METHOD = 'ADD_NEW_INTERFACE_METHOD'
}

export default ClassDiagramActionEnum;