enum ClassTypeEnum {
    UTILITY = 'UTILITY', 
    TEMPLATE = 'TEMPLATE',
    INTERFACE = 'INTERFACE',
    DATA_TYPE = 'DATA_TYPE',
    PRIMITIVE_TYPE = 'PROMITIVE_TYPE',
    ENUMERATION = 'ENUMERATION'
}

export default ClassTypeEnum;