enum RibbonOperationEnum {
    ADD_NEW_CLASS = 'ADD_NEW_CLASS',
    ADD_NEW_EMPTY_CLASS = 'ADD_NEW_EMPTY_CLASS',
    ADD_NEW_INTERFACE = 'ADD_NEW_INTERFACE',
    ADD_NEW_UTILITY = 'ADD_NEW_UTILITY',
    ADD_NEW_DATA_TYPE = 'ADD_NEW_DATA_TYPE',
    ADD_NEW_ENUMERATION = 'ADD_NEW_ENUMERATION',
    ADD_NEW_PRIMITIVE_TYPE = 'ADD_NEW_PRIMITIVE_TYPE',
    ADD_NEW_OBJECT = 'ADD_NEW_OBJECT'
}

export default RibbonOperationEnum;