enum RibbonOperationEnum {
    ADD_NEW_CLASS = 'ADD_NEW_CLASS',
    ADD_NEW_EMPTY_CLASS = 'ADD_NEW_EMPTY_CLASS',
    ADD_NEW_INTERFACE = 'ADD_NEW_INTERFACE',
    ADD_NEW_UTILITY = 'ADD_NEW_UTILITY',
    ADD_NEW_DATA_TYPE = 'ADD_NEW_DATA_TYPE',
    ADD_NEW_ENUMERATION = 'ADD_NEW_ENUMERATION',
    ADD_NEW_PRIMITIVE_TYPE = 'ADD_NEW_PRIMITIVE_TYPE',
    ADD_NEW_OBJECT = 'ADD_NEW_OBJECT',
    ADD_NEW_SIMPLE_STATE = 'ADD_NEW_SIMPLE_STATE',
    ADD_NEW_STATE = 'ADD_NEW_STATE',
    ADD_NEW_INITIAL_STATE = 'ADD_NEW_INITIAL_STATE',
    ADD_NEW_FINAL_STATE = 'ADD_NEW_FINAL_STATE',
    ADD_NEW_FORK_JOIN = 'ADD_NEW_FORK_JOIN',
    ADD_NEW_CHOICE = 'ADD_NEW_CHOICE'
}

export default RibbonOperationEnum;