enum StateDiagramActionEnum {
    ADD_NEW_STATE_ELEMENT = 'ADD_NEW_STATE_ELEMENT',
    UPDATE_STATE_ELEMENT = 'UPDATE_STATE_ELEMENT',
    ADD_NEW_INITIAL_STATE_ELEMENT = 'ADD_NEW_INITIAL_STATE_ELEMENT',
    UPDATE_INITIAL_STATE_ELEMENT = 'UPDATE_INITIAL_STATE_ELEMENT',
    ADD_NEW_FINAL_STATE_ELEMENT = 'ADD_NEW_FINAL_STATE_ELEMENT',
    UPDATE_FINAL_STATE_ELEMENT = 'UPDATE_FINAL_STATE_ELEMENT',
    ADD_NEW_FORK_JOIN = 'ADD_NEW_FORK_JOIN',
    UPDATE_FORK_JOIN = 'UPDATE_FORK_JOIN',
    ADD_NEW_CHOICE = 'ADD_NEW_CHOICE',
    UPDATE_CHOICE = 'UPDATE_CHOICE'
}

export default StateDiagramActionEnum;