enum StateDiagramActionEnum {
    ADD_NEW_STATE_ELEMENT = 'ADD_NEW_STATE_ELEMENT',
    UPDATE_STATE_ELEMENT = 'UPDATE_STATE_ELEMENT',
    ADD_NEW_INITIAL_STATE_ELEMENT = 'ADD_NEW_INITIAL_STATE_ELEMENT',
    UPDATE_INITIAL_STATE_ELEMENT = 'UPDATE_INITIAL_STATE_ELEMENT',
    ADD_NEW_FINAL_STATE_ELEMENT = 'ADD_NEW_FINAL_STATE_ELEMENT',
    UPDATE_FINAL_STATE_ELEMENT = 'UPDATE_FINAL_STATE_ELEMENT',
    ADD_NEW_FORK_JOIN = 'ADD_NEW_FORK_JOIN',
    UPDATE_FORK_JOIN = 'UPDATE_FORK_JOIN',
    ADD_NEW_CHOICE = 'ADD_NEW_CHOICE',
    UPDATE_CHOICE = 'UPDATE_CHOICE',
    ADD_NEW_STATE_RELATIONSHIP = 'ADD_NEW_STATE_RELATIONSHIP',
    UPDATE_STATE_RELATIONSHIP = 'UPDATE_STATE_RELATIONSHIP',
    ADD_NEW_STATE_RELATIONSHIP_SEGMENT = 'ADD_NEW_STATE_RELATIONSHIP_SEGMENT',
    UPDATE_STATE_RELATIONSHIP_SEGMENT = 'UPDATE_STATE_RELATIONSHIP_SEGMENT',
    REMOVE_STATE_RELATIONSHIP_SEGMENT = 'REMOVE_STATE_RELATIONSHIP_SEGMENT',
    REMOVE_STATE_RELATIONSHIP = 'REMOVE_STATE_RELATIONSHIP',
    ADD_NEW_NEW_STATE_RELATIONSHIP = 'ADD_NEW_NEW_STATE_RELATIONSHIP',
    UPDATE_NEW_STATE_RELATIONSHIP = 'UPDATE_NEW_STATE_RELATIONSHIP',
    CLEAR_NEW_STATE_RELATIONSHIP = 'CLEAR_NEW_STATE_RELATIONSHIP',
    CLEAR_STATE_ELEMENTS = 'CLEAR_STATE_ELEMENTS',
    CLEAR_FINAL_STATE_ELEMENTS = 'CLEAR_FINAL_STATE_ELEMENTS',
    CLEAR_INITIAL_STATE_ELEMENTS = 'CLEAR_FINAL_STATE_ELEMENTS'
}

export default StateDiagramActionEnum;